### ISSUE TITLE
Evolve into a script pack

### ISSUE THREAD

**Issue by adamralph** [andreasohlund/NServiceBus.ScriptCs#1]
This is great work and I think an ideal candidate for a script pack! https://github.com/scriptcs/scriptcs/wiki/Authoring-script-packs

**Comment by andreasohlund** [comment]
Thanks, I haven't touched this in a while. Would you be able to help out?

**Comment by adamralph** [comment]
I've never used NServiceBus so probably not best qualified to actually code it, but I'd be glad to offer any info that might be needed. I have a lot on right now but when I get a chance I can quickly sketch how I think the code could look.
